CREATE TABLE geo_movies (
    unique_id	INT,
    Title	VARCHAR(512),
    Air_date	INT,
    TP_min	INT,
    Rating	DOUBLE PRECISION,
    Votes	INT
);

INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('1', ' Gamis zarebi', '1997', '95', '9.8', '5');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('2', ' The Shards', '2024', '90', '7.8', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('3', ' Chakluli suli', '1994', '75', '7.8', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('4', ' Jara', '2017', '52', '8.2', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('5', ' Ochabamba', '1994', '75', '7.4', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('6', ' Enki-Benki', '2002', '80', '8.4', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('7', ' All about People', '2015', '71', '7.0', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('8', ' Tskals sazghvrebi ar akvs', '2021', '85', '8.4', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('9', ' Mokvetili', '1992', '95', '7.4', '6');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('11', ' Midi Dzmao, Midi!', '2011', '90', '8.2', '7');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('13', ' The Many Faces of Comrade Gelovani', '2014', '67', '7.2', '7');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('16', ' When Time Passes', '2024', '53', '8.5', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('17', ' Hamlet', '2017', '93', '7.9', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('20', ' Eqvsi da shvidi', '2004', '67', '7.6', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('21', ' Maidan, Nave of the World', '2005', '50', '7.8', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('22', ' Khveuli kibit', '2001', '90', '7.0', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('24', ' Tsarieli sivrtse', '2001', '97', '7.8', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('26', ' Gvinis Akvani', '2013', '62', '9.6', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('27', ' Natlisgeba', '1994', '76', '5.4', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('28', ' Sanam Mama Dabrundeba', '2018', '75', '7.1', '8');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('29', ' 87 Candles', '2024', '55', '8.9', '9');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('30', ' Mister Dzidza', '2013', '100', '6.6', '9');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('31', ' Izi da jadokari', '2019', '68', '6.7', '9');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('32', ' Pastor Paul', '2015', '67', '5.8', '9');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('33', ' Month as a Day', '2016', '128', '7.9', '9');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('35', ' From Life to Life', '2023', '90', '8.6', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('37', ' Sakartvelo', '2023', '115', '8.6', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('38', ' Delirium', '2003', '65', '7.4', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('39', ' A Wolf\s Psychology', '2009', '112', '7.6', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('41', ' Kidev erti qartuli istoria', '2003', '89', '7.1', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('43', ' Luka', '2016', '81', '7.6', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('44', ' 1+1-1', '2023', '13', '9.2', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('45', ' Spam', '2010', '90', '5.8', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('47', ' Napitsi Msajuli', '2010', '120', '6.8', '10');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('48', ' The Migration of the Angel', '2001', '77', '8.4', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('49', ' Adopted', '2011', '99', '7.6', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('50', ' Night Dance', '1991', '128', '5.4', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('51', ' Leonardo', '1993', '90', '6.7', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('52', ' Biblioteka', '2014', '54', '5.8', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('53', ' Bluzi', '1994', '92', '7.4', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('54', ' Bediani', '1992', '100', '8.0', '11');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('56', ' Gamodi', '2023', '98', '5.9', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('57', ' Autaneli Ardadegebi', '2015', '90', '7.2', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('58', ' I Didn\t Cross the Border: The Border Crossed Me', '2016', '80', '6.5', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('65', ' Matskhovris Saplavze Antebuli Santeli', '2008', '125', '8.2', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('66', ' Threshold', '2020', '64', '5.0', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('67', ' Didube, the Last Stop', '2017', '64', '9.0', '12');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('68', ' English Teacher', '2012', '56', '8.3', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('69', ' Reverse', '2006', '56', '7.5', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('70', ' Inconceivable Light', '2022', '82', '8.2', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('73', ' Bambaziis samotxe', '2010', '75', '8.2', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('74', ' Man', '2018', '98', '8.9', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('75', ' Sergo Gotorani', '2009', '48', '7.9', '13');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('76', ' Transparent World', '2018', '82', '7.0', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('77', ' Sakhli Sikharulisa', '2009', '70', '6.4', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('78', ' Double Aliens', '2015', '56', '7.8', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('79', ' Six Days', '2013', '56', '7.4', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('80', ' Family', '2017', '45', '7.0', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('81', ' 11Eleven Project', '2012', '75', '7.8', '14');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('82', ' Peplebis idzulebiti migratsia', '2023', '90', '7.4', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('83', ' Blueberry Dreams', '2024', '75', '7.9', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('84', ' The Harvest', '2019', '70', '5.6', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('85', ' The Drummer', '2022', '84', '7.1', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('86', ' How the Room Felt', '2021', '74', '6.9', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('87', ' Gza tadzrisken', '1994', '80', '8.4', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('88', ' #standwithme', '2014', '73', '7.5', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('89', ' Kventinis Satvale', '2008', '93', '3.7', '15');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('90', ' Devout', '2016', '88', '9.1', '16');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('91', ' Rais Nasosi', '2015', '90', '8.1', '16');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('92', ' Imagining Emanuel', '2011', '52', '5.2', '16');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('93', ' What to Do with All This Love', '2022', '80', '7.2', '16');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('94', ' Saving Papua by Not Cycling There', '2014', '85', '5.6', '17');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('95', ' Deda-Shvili an ghame ar aris arasodes bolomde bneli', '2024', '89', '8.2', '18');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('98', ' Omi da Qortsili', '2010', '105', '4.8', '18');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('99', ' All that Passes By Through a Window That Doesn\t Open', '2017', '70', '7.4', '18');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('100', ' Vegetable garden in the conflict zone', '2022', '84', '8.7', '18');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('102', ' Mkholod sikvdili modis autsileblad', '1992', '130', '7.6', '19');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('103', ' 5 Dreamers and a Horse', '2022', '80', '7.3', '20');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('104', ' Expres-Inpormatsia', '1994', '105', '8.1', '20');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('106', ' Don Juanis dabadeba', '1995', '125', '7.8', '20');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('108', ' Tatli Süt Köpügü', '2022', '109', '5.5', '21');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('109', ' Shadows of the Empire', '2019', '76', '5.3', '21');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('110', ' Tsarsulis achrdilebi', '1995', '114', '8.4', '21');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('111', ' Hotel Metalurg', '2023', '71', '8.0', '21');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('115', ' Life and Death of a Christmas Tree', '2023', '84', '8.0', '22');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('116', ' Aghdgoma', '2022', '94', '8.2', '22');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('117', ' Zgvarze', '1993', '77', '7.5', '22');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('118', ' Posledniy iskatel', '2006', '92', '4.4', '22');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('119', ' Budapest inferno: The Secret of the Molnar Janos Cave', '2017', '51', '8.2', '22');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('120', ' 3+3', '2015', '88', '5.0', '23');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('123', ' Bakhmaro heißt Paradies', '2011', '59', '7.5', '24');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('124', ' kai to treno paei ston ourano', '2001', '94', '5.8', '24');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('126', ' The Return', '2023', '105', '6.3', '25');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('127', ' Dead Souls\ Vacation', '2020', '66', '8.7', '25');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('128', ' Teen Spirit', '2012', '84', '8.2', '26');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('129', ' Isini', '1992', '142', '7.0', '26');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('130', ' Netavi ik teatri aris?!', '2011', '55', '9.1', '26');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('131', ' Self-Portrait Along the Borderline', '2023', '50', '8.1', '26');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('132', ' In the Name of Blood', '2024', '108', '7.6', '27');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('133', ' See You in Chechnya', '2016', '69', '7.0', '27');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('134', ' Orpeosis sikvdili', '1996', '85', '7.5', '27');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('135', ' Midjachvuli raindebi', '2000', '91', '8.0', '27');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('136', ' Antimoz iverieli', '2001', '210', '8.4', '27');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('137', ' The Enemies', '2017', '66', '7.9', '28');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('138', ' Subordinacia', '2007', '78', '6.1', '28');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('139', ' Life is Be', '2016', '87', '8.2', '28');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('140', ' The Waltz on the Petschora', '1992', '108', '6.9', '29');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('142', ' Abandoned?', '2013', '65', '4.1', '29');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('143', ' Lukas sakhareba', '1998', '72', '8.4', '29');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('145', ' The Resting Samurai', '2022', '107', '6.5', '30');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('146', ' Ori', '2009', '85', '7.0', '31');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('147', ' Nutsas skola', '2000', '114', '7.5', '31');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('148', ' Krapiva: Tsvetok smerti', '2024', '81', '5.7', '32');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('150', ' The Watchmaker', '2011', '90', '8.0', '32');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('152', ' Enemies', '2017', '65', '8.7', '32');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('153', ' Jadosnuri Mta', '2023', '73', '6.9', '34');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('154', ' Otsnebebis sasaplao', '1997', '90', '7.5', '34');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('156', ' Gogona Slaididan', '2009', '115', '5.0', '35');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('158', ' Svani', '2007', '90', '7.1', '37');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('159', ' Ra Mokhda Kievshi', '2013', '78', '5.5', '37');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('161', ' Patient No 1', '2023', '110', '7.4', '38');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('162', ' Gift', '2013', '50', '8.4', '38');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('163', ' Find Your Body', '2012', '110', '7.0', '39');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('164', ' Botso', '2014', '82', '9.1', '39');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('165', ' Curator', '2019', '76', '4.9', '39');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('166', ' Teper ya budu lyubyty tebe', '2015', '93', '6.2', '39');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('167', ' Enticing, Sugary, Boundless or Songs and Dances About Death', '2017', '96', '8.3', '40');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('168', ' Dabadebulebi Saqartveloshi', '2011', '81', '6.5', '41');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('169', ' Jakos Khiznebi', '2009', '110', '6.6', '41');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('170', ' Ursus', '2020', '110', '6.2', '42');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('171', ' Beautiful Helen', '2022', '92', '5.8', '42');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('172', ' Something About Georgia', '2009', '90', '8.3', '43');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('173', ' God of Happiness', '2015', '93', '7.5', '44');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('174', ' Garigeba 20 Tslis Shemdeg', '2011', '100', '4.8', '45');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('176', ' Marilivit Tetri', '2011', '85', '6.3', '46');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('177', ' Ak tendeba', '1998', '90', '7.0', '46');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('178', ' The Antique', '2024', '132', '7.0', '47');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('179', ' Ramin', '2011', '58', '7.4', '47');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('180', ' A Tunnel', '2019', '92', '7.5', '47');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('181', ' And the Sun Rises', '2022', '90', '6.4', '48');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('182', ' Tskhra mtas iqit', '2015', '112', '6.7', '49');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('184', ' Liza, go on', '2023', '120', '5.7', '50');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('185', ' Smiling Georgia', '2023', '62', '7.2', '50');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('186', ' Golden Thread', '2019', '90', '7.3', '51');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('187', ' Stay with Me', '2011', '79', '5.0', '51');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('188', ' Tbilisuri Love Story', '2009', '77', '5.3', '52');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('190', ' The Knight in Tiger\s Skin', '2022', '108', '7.3', '54');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('191', ' The Chair', '2017', '97', '6.1', '56');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('192', ' Nina', '2023', '110', '5.4', '57');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('195', ' The Parts', '2013', '90', '6.7', '57');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('196', ' The Forgotten King', '2014', '110', '7.7', '59');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('197', ' Gogita\s New Life', '2016', '74', '8.3', '60');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('200', ' Samotkhis gvritebi', '1997', '60', '8.6', '63');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('201', ' Pig', '2019', '80', '7.5', '64');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('202', ' Everybody\s Gone', '2013', '115', '6.5', '64');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('203', ' Panopticon', '2024', '95', '8.0', '65');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('204', ' Lotto', '2023', '84', '6.9', '65');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('205', ' A Long Break', '2022', '110', '6.6', '66');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('206', ' Datuna: Portrait of America', '2015', '77', '8.9', '66');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('207', ' I Am Truly a Drop of Sun on Earth', '2017', '61', '6.0', '67');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('208', ' Arsena Jorjiashvili', '1921', '50', '5.9', '69');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('209', ' Judgement Night', '2017', '109', '7.8', '70');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('210', ' Parade', '2018', '87', '7.0', '70');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('211', ' Ormagi sakhe', '1996', '84', '8.0', '70');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('212', ' Taxi', '2014', '107', '7.4', '73');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('213', ' Seagull', '2012', '100', '7.3', '73');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('214', ' Light Falls', '2023', '95', '6.1', '74');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('215', ' My Dad\s Girlfriend', '2011', '102', '5.0', '75');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('217', ' Holy Electricity', '2024', '104', '7.3', '78');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('218', ' Criminals', '2015', '75', '7.0', '78');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('219', ' Like Cotton Twines', '2016', '96', '7.8', '79');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('220', ' Women from Georgia', '2009', '54', '7.0', '80');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('222', ' Glory to the Queen', '2020', '82', '7.4', '82');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('226', ' The Summer of Frozen Fountains', '2015', '103', '7.0', '86');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('227', ' The Adventures of Ano & Vano', '2011', '105', '6.8', '89');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('229', ' Mediator', '2008', '92', '8.1', '93');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('230', ' Rac kvelaze dzalian gikvars 2', '2009', '112', '6.7', '94');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('232', ' Chomu ya zhyvyy', '2021', '120', '7.2', '96');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('233', ' Let the Summer Never Come Again', '2017', '202', '6.2', '99');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('234', ' Don\t Breathe', '2014', '86', '6.4', '101');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('235', ' Inhale-Exhale', '2019', '91', '6.2', '101');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('236', ' Black Diamond', '2010', '101', '7.5', '102');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('237', ' Idiotocratia', '2008', '115', '7.1', '104');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('238', ' I\m Beso', '2014', '91', '7.0', '105');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('239', ' Bebia, à mon seul désir', '2021', '113', '6.4', '107');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('240', ' The Last Fortress: Hacibey', '2020', '100', '5.8', '110');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('241', ' Anna\s Life', '2016', '108', '6.7', '111');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('243', ' I Will Die Without You', '2010', '100', '7.6', '112');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('245', ' When the Earth Seems to Be Light', '2015', '76', '7.4', '113');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('246', ' Neighbors', '2018', '90', '7.8', '115');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('247', ' Citizen Saint', '2023', '100', '7.4', '116');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('248', ' Chuzhaya molitva', '2017', '100', '7.6', '116');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('249', ' Tbilisi-Tbilisi', '2005', '87', '7.3', '117');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('250', ' Horizonti', '2018', '105', '6.9', '117');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('251', ' Chama da Sex', '2011', '85', '6.2', '120');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('253', ' Line of Credit', '2014', '125', '6.7', '121');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('254', ' Raving riot', '2019', '62', '7.2', '125');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('255', ' Rene Goes to Hollywood', '2010', '103', '6.5', '130');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('256', ' Maita Nasosi', '2010', '90', '5.1', '138');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('257', ' Sahä', '2010', '118', '6.7', '138');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('258', ' The Dazzling Light of Sunset', '2016', '74', '6.2', '140');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('259', ' The Criminal Man', '2019', '135', '5.6', '147');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('260', ' Rac kvelaze dzalian gikvars', '2008', '112', '6.9', '148');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('261', ' Bo', '2022', '120', '6.5', '151');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('263', ' Otar\s Death', '2021', '107', '6.7', '155');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('264', ' Brides', '2014', '94', '7.0', '156');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('266', ' The Narrow Bridge', '2022', '80', '7.3', '159');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('268', ' Koma', '2013', '90', '7.6', '165');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('269', ' Ertkhel Shua Qalaqshi', '2011', '90', '6.3', '174');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('270', ' Moira', '2015', '95', '7.0', '176');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('271', ' Bekleyis', '2021', '67', '6.3', '177');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('272', ' Kvelaferi kargad iqneba', '2009', '94', '6.1', '183');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('273', ' The Rainbowmaker', '2008', '90', '6.2', '183');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('274', ' Rusuli samkudhedi', '2007', '121', '6.7', '191');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('275', ' Susa', '2010', '75', '6.5', '194');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('276', ' Tba', '1998', '87', '7.3', '197');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('277', ' A Fold in My Blanket', '2013', '73', '5.3', '199');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('278', ' Russian Lessons', '2010', '110', '7.8', '201');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('279', ' SeaZone', '2010', '106', '5.2', '204');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('280', ' Janapar', '2012', '79', '7.0', '208');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('281', ' Khibula', '2017', '97', '5.5', '212');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('282', ' Power Trip', '2003', '86', '7.3', '231');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('283', ' Midioda matarebeli', '2005', '77', '6.4', '232');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('285', ' Gondola', '2023', '82', '6.7', '235');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('286', ' Negative Numbers', '2019', '110', '7.3', '242');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('287', ' Tbilisi, I Love You', '2014', '93', '6.4', '246');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('288', ' House of Others', '2016', '103', '6.2', '261');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('289', ' The Confession', '2017', '89', '6.3', '261');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('290', ' Lost in Karastan', '2014', '96', '5.1', '273');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('291', ' Dzma', '2014', '94', '6.7', '275');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('292', ' Anton', '2019', '102', '6.7', '279');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('293', ' Namme', '2017', '91', '7.3', '280');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('294', ' April', '2024', '134', '6.3', '281');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('295', ' The Redemption of General Butt Naked', '2011', '85', '7.4', '293');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('296', ' Gzaabneulni', '2013', '80', '7.9', '297');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('298', ' Comets', '2019', '70', '6.0', '302');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('299', ' City of the Sun', '2017', '104', '7.0', '314');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('300', ' Iavnana', '1994', '75', '7.8', '315');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('301', ' Sami Sakhli', '2009', '96', '7.6', '334');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('302', ' Paradzhanov', '2013', '95', '6.7', '337');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('303', ' The Conflict Zone', '2009', '82', '8.1', '360');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('304', ' Pelada', '2010', '90', '7.5', '362');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('305', ' Winter Song', '2015', '117', '6.2', '364');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('306', ' Brigands', '1996', '129', '7.0', '371');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('307', ' Tea', '2017', '72', '7.2', '375');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('308', ' SAZ- the Key of Trust', '2018', '90', '8.4', '386');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('309', ' A Room of My Own', '2022', '107', '6.2', '389');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('310', ' Chantrapas', '2010', '122', '6.2', '393');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('311', ' Lyubov s aktsentom', '2012', '100', '5.4', '418');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('313', ' Apocalypse Will Not Happen', '2015', '79', '8.5', '512');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('315', ' Mamas Heart Gongadze', '2017', '77', '7.7', '549');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('316', ' Bolo gaseirneba', '2012', '93', '7.7', '573');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('317', ' Scary Mother', '2017', '107', '6.8', '602');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('318', ' Blind Dates', '2013', '99', '7.1', '624');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('319', ' Keep Smiling', '2012', '90', '7.1', '624');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('320', ' The Other Me', '2022', '108', '4.2', '698');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('321', ' The Machine Which Makes Everything Disappear', '2012', '97', '8.1', '701');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('322', ' Poverty, Inc', '2014', '94', '7.6', '734');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('323', ' Wet Sand', '2021', '115', '7.0', '755');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('324', ' Taming the Garden', '2021', '91', '6.9', '755');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('325', ' L\héritage', '2006', '75', '6.9', '768');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('327', ' A Chef in Love', '1996', '100', '6.6', '842');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('328', ' Shindisi', '2019', '101', '7.3', '943');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('329', ' SlingShot', '2014', '88', '7.7', '952');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('330', ' A Trip to Karabakh', '2005', '105', '7.8', '997');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('331', ' Brighton 4th', '2021', '90', '6.8', '1000');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('332', ' Dede', '2017', '97', '6.9', '1100');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('333', ' Street Days', '2010', '89', '7.7', '1300');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('334', ' Gagma napiri', '2009', '90', '7.7', '1400');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('335', ' Blackbird Blackbird Blackberry', '2023', '110', '7.0', '1400');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('336', ' 27 Missing Kisses', '2000', '98', '6.6', '1500');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('337', ' Sun of the Sleepless', '1992', '123', '8.4', '1700');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('338', ' Tatami', '2023', '105', '7.5', '1800');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('339', ' Let It Snow', '2020', '87', '4.4', '1900');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('340', ' The President', '2014', '119', '7.3', '1900');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('341', ' Memories of the Wind', '2015', '124', '7.0', '1900');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('342', ' Hostages', '2017', '103', '6.1', '2100');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('343', ' What Do We See When We Look at the Sky?', '2021', '150', '6.8', '2200');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('344', ' Beginning', '2020', '130', '6.6', '2500');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('346', ' Depuis qu\Otar est parti', '2003', '103', '7.5', '2700');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('347', ' Ekvtime: Man of God', '2018', '132', '7.3', '2800');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('349', ' Girls of the Sun', '2018', '115', '6.5', '2900');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('350', ' The Search', '2014', '135', '6.8', '3000');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('351', ' Crossing', '2024', '106', '7.5', '3600');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('352', ' My Happy Family', '2017', '120', '7.4', '4300');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('353', ' Corn Island', '2014', '100', '7.4', '4700');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('354', ' Zana', '2019', '97', '7.1', '4800');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('355', ' Landmine Goes Click', '2015', '105', '5.8', '6800');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('356', ' 247°F', '2011', '88', '4.8', '7000');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('357', ' In Bloom', '2013', '102', '7.3', '7200');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('358', ' 5 Days of War', '2011', '113', '5.5', '14000');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('359', ' And Then We Danced', '2019', '113', '7.6', '15000');
INSERT INTO geo_movies (unique_id, Title, Air_date, TP_min, Rating, Votes) VALUES ('360', ' Tangerines', '2013', '87', '8.1', '50000');
